experiment_name: "solo_distilgpt2"

single_model:
  model_name: "distilgpt2"
  batch_size: 4
  seq_len: 16
  num_warmup: 10
  num_iters: 200
  device: "cuda"
  out_dir: "experiments/logs/no_mps/"
  tag: "solo"
