experiment_name: "3_llama"
mps: True
sleep_duration: 120
device: "cuda"

tenants:
  - model_name: "meta-llama/Llama-3.2-3B-Instruct"
    name: "llama3.2_3b_1"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10

  - model_name: "meta-llama/Llama-3.2-3B-Instruct"
    name: "llama3.2_3b_2"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10

  - model_name: "meta-llama/Llama-3.2-3B-Instruct"
    name: "llama3.2_3b_3"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10
