experiment_name: "bert_roberta"
mps: True
sleep_duration: 120
device: "cuda"

tenants:
  - model_name: "distilbert-base-uncased"
    name: "distilbert"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10

  - model_name: "roberta-large"
    name: "roberta_large"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10
