experiment_name: "distilbert_mistral"
mps: True
sleep_duration: 120
device: "cuda"

tenants:
  - model_name: "distilbert-base-uncased"
    name: "distilbert"
    batch_size: 8
    seq_len: 128
    num_iters: 200
    num_warmup: 10

  - model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    name: "mistral7b"
    batch_size: 8
    seq_len: 128
    num_iters: 200
    num_warmup: 10
