experiment_name: "mps_distilGPT2_mistral7b"
mps: True
sleep_duration: 120 #sleep duration in seconds
device: "cuda"


tenants:
  - model_name: "distilgpt2"
    name: "distilgpt2"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10

  - model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    name: "mistral7b"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10
