experiment_name: "experiment_name" # Name of data output directory
mps: True/ False # Whether or not to run with Nvidia MPS
sleep_duration: 120
device: "cuda" # Currently only supports cuda

# TODO make sure this is consistent with scripts and solo model config format

tenants:
  - model_name: "model name as found on Hugging Face"
    name: "name shorthand or same as above" # Name of this model's directory in the output data
    batch_size: 16
    seq_len: 128
    num_iters: 200
    num_warmup: 10

  # If multiple tenants are the same model, ensure the name fields are different
  #   to prevent overwriting the output file.
  # For example:
  - model_name: "mistralai/Mistral-7B-Instuct-v0.2"
    name: "mistral7b_1"
    batch_size: 8
    seq_len: 512
    num_iters: 200
    num_warmup: 10

  - model_name: "mistralai/Mistral-7B-Instuct-v0.2"
    name: "mistral7b_2"
    batch_size: 8
    seq_len: 512
    num_iters: 200
    num_warmup: 10
