experiment_name: "experiment name"
mps: true/false
sleep_duration: 120 #sleep duration in seconds
device: "cuda"

# TODO make sure this is consistent with scripts and solo model config format

tenants:
  - model_name: "model name as found on Hugging Face"
    name: "name shorthand or same as above"
    batch_size: 16
    seq_len: 128
    num_iters: 200
    num_warmup: 10

  - model_name: "mistralai/Mistral-7B-Instuct-v0.2"
    name: "mistral7b"
    batch_size: 8
    seq_len: 512
    num_iters: 200
    num_warmup: 10
