experiment_name: "pair_distilGPT2"
mps: false
sleep_duration: 120 #sleep duration in seconds
device: "cuda"


tenants:
  - model_name: "distilgpt2"
    name: "distilgpt2_1"
    batch_size: 16
    seq_len: 128
    num_iters: 200
    num_warmup: 10

  - model_name: "distilgpt2"
    name: "distilgpt2_2"
    batch_size: 16
    seq_len: 128
    num_iters: 200
    num_warmup: 10
