experiment_name: "pair_mistral7b"
mps: True
sleep_duration: 120
device: "cuda"

tenants:
  - model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    name: "mistral7b_1"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10

  - model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    name: "mistral7b_2"
    batch_size: 8
    seq_len: 128
    num_iters: 100
    num_warmup: 10
